import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { defaultReactDevCommand, saveDesignProjectConfig } from "./project-config";
import type { DesignProjectKind } from "./types";

export async function scaffoldDesignProject(projectPath: string, kind: DesignProjectKind): Promise<void> {
  if (kind === "react") {
    await scaffoldReactProject(projectPath);
    return;
  }
  await saveDesignProjectConfig(projectPath, { kind: "html" });
}

async function scaffoldReactProject(projectPath: string): Promise<void> {
  await mkdir(join(projectPath, "src"), { recursive: true });
  await saveDesignProjectConfig(projectPath, {
    kind: "react",
    devCommand: defaultReactDevCommand(),
  });
  await Promise.all([
    writeFile(join(projectPath, "package.json"), reactPackageJson(), "utf8"),
    writeFile(join(projectPath, "index.html"), reactIndexHtml(), "utf8"),
    writeFile(join(projectPath, "src", "main.tsx"), reactMainSource(), "utf8"),
    writeFile(join(projectPath, "src", "App.tsx"), reactAppSource(), "utf8"),
    writeFile(join(projectPath, "src", "aflow-design-bridge.ts"), reactBridgeSource(), "utf8"),
    writeFile(join(projectPath, "src", "style.css"), reactStyleSource(), "utf8"),
    writeFile(join(projectPath, "manifest.json"), reactManifestJson(), "utf8"),
    writeFile(join(projectPath, "desktop.md"), reactDescriptionMarkdown("Desktop"), "utf8"),
    writeFile(join(projectPath, "mobile.md"), reactDescriptionMarkdown("Mobile"), "utf8"),
  ]);
}

function reactPackageJson(): string {
  return `${JSON.stringify({
    type: "module",
    scripts: {
      dev: "vite",
    },
    dependencies: {
      "@vitejs/plugin-react": "^5.1.0",
      vite: "^7.2.2",
      typescript: "^5.9.3",
      react: "^19.2.0",
      "react-dom": "^19.2.0",
    },
    devDependencies: {},
  }, null, 2)}\n`;
}

function reactIndexHtml(): string {
  return [
    "<!doctype html>",
    "<html>",
    "  <head>",
    "    <meta charset=\"UTF-8\" />",
    "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />",
    "    <title>Aflow Designer React Project</title>",
    "  </head>",
    "  <body>",
    "    <div id=\"root\"></div>",
    "    <script type=\"module\" src=\"/src/main.tsx\"></script>",
    "  </body>",
    "</html>",
    "",
  ].join("\n");
}

function reactMainSource(): string {
  return [
    "import React from \"react\";",
    "import { createRoot } from \"react-dom/client\";",
    "import { App } from \"./App\";",
    "import { initializeAflowDesignBridge } from \"./aflow-design-bridge\";",
    "import \"./style.css\";",
    "",
    "initializeAflowDesignBridge();",
    "",
    "createRoot(document.getElementById(\"root\")!).render(",
    "  <React.StrictMode>",
    "    <App />",
    "  </React.StrictMode>,",
    ");",
    "",
  ].join("\n");
}

function reactAppSource(): string {
  return [
    "function currentFrame() {",
    "  const route = window.location.pathname.replace(/^\\/+/, \"\") || \"desktop\";",
    "  const view = new URLSearchParams(window.location.search).get(\"view\") || \"html\";",
    "  return { route, wireframe: view === \"wireframe\" };",
    "}",
    "",
    "export function App() {",
    "  const { route, wireframe } = currentFrame();",
    "  if (route === \"mobile\") return <MobileFrame wireframe={wireframe} />;",
    "  return <DesktopFrame wireframe={wireframe} />;",
    "}",
    "",
    "function DesktopFrame({ wireframe }: { wireframe: boolean }) {",
    "  return (",
    "    <main className={`design-frame desktop ${wireframe ? \"wireframe\" : \"\"}`} data-component-id=\"desktop.shell\" data-component-name=\"Desktop shell\">",
    "      <section className=\"hero\" data-component-id=\"desktop.hero\" data-component-name=\"Hero\">",
    "        <p className=\"eyebrow\">React Designer Project</p>",
    "        <h1>Start designing in React</h1>",
    "        <p>Ask the Designer agent to replace this scaffold with your product interface.</p>",
    "      </section>",
    "    </main>",
    "  );",
    "}",
    "",
    "function MobileFrame({ wireframe }: { wireframe: boolean }) {",
    "  return (",
    "    <main className={`design-frame mobile ${wireframe ? \"wireframe\" : \"\"}`} data-component-id=\"mobile.shell\" data-component-name=\"Mobile shell\">",
    "      <section className=\"mobile-card\" data-component-id=\"mobile.hero\" data-component-name=\"Mobile hero\">",
    "        <p className=\"eyebrow\">Mobile</p>",
    "        <h1>React frame</h1>",
    "        <p>This route shares code with the desktop frame.</p>",
    "      </section>",
    "    </main>",
    "  );",
    "}",
    "",
  ].join("\n");
}

function reactStyleSource(): string {
  return [
    ":root {",
    "  font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, \"Segoe UI\", sans-serif;",
    "  color: #172018;",
    "  background: #f6f8f1;",
    "}",
    "",
    "* { box-sizing: border-box; }",
    "html, body, #root { margin: 0; min-height: 100%; }",
    "body { width: 100%; overflow-x: visible; }",
    "",
    ".design-frame {",
    "  width: 100%;",
    "  max-width: none;",
    "  min-height: 100vh;",
    "  padding: 48px;",
    "  background: #f6f8f1;",
    "}",
    "",
    ".hero, .mobile-card {",
    "  border: 1px solid #d8dfcf;",
    "  background: #ffffff;",
    "  border-radius: 8px;",
    "  padding: 32px;",
    "}",
    "",
    ".eyebrow { margin: 0 0 12px; color: #54715f; font-size: 12px; font-weight: 700; text-transform: uppercase; }",
    "h1 { margin: 0 0 12px; font-size: 48px; line-height: 1.05; letter-spacing: 0; }",
    "p { margin: 0; color: #526057; font-size: 16px; line-height: 1.5; }",
    "",
    ".mobile { padding: 24px; }",
    ".mobile h1 { font-size: 34px; }",
    "",
    ".wireframe * {",
    "  color: #263025 !important;",
    "  background: transparent !important;",
    "  box-shadow: none !important;",
    "}",
    ".wireframe [data-component-id] { outline: 1px dashed #7a8779; }",
    "",
  ].join("\n");
}

function reactManifestJson(): string {
  return `${JSON.stringify({
    frames: [
      {
        id: "desktop",
        title: "Desktop",
        kind: "desktop",
        width: 1440,
        height: 1024,
        x: 0,
        y: 0,
        route: "/desktop",
        descriptionPath: "desktop.md",
      },
      {
        id: "mobile",
        title: "Mobile",
        kind: "mobile",
        width: 390,
        height: 844,
        x: 1520,
        y: 0,
        route: "/mobile",
        descriptionPath: "mobile.md",
      },
    ],
  }, null, 2)}\n`;
}

function reactDescriptionMarkdown(title: string): string {
  return [
    `# ${title}`,
    "",
    "Initial React frame scaffold. Update this file whenever the design intent, structure, interactions, states, or tradeoffs change.",
    "",
  ].join("\n");
}

function reactBridgeSource(): string {
  return [
    "type DesignNode = HTMLElement & { dataset: DOMStringMap };",
    "",
    "const ignoredTags = new Set([\"HTML\", \"HEAD\", \"BODY\", \"SCRIPT\", \"STYLE\", \"META\", \"LINK\", \"TITLE\", \"NOSCRIPT\", \"TEMPLATE\"]);",
    "const layerColors = [\"#0ea5e9\", \"#8b5cf6\", \"#f97316\", \"#22c55e\", \"#e11d48\", \"#14b8a6\", \"#f59e0b\"];",
    "",
    "let selectedComponentId = \"\";",
    "let hoverId = \"\";",
    "let domCounter = 0;",
    "let styleDrafts: Record<string, Record<string, string>> = {};",
    "let draftedIds = new Set<string>();",
    "",
    "export function initializeAflowDesignBridge() {",
    "  if (typeof window === \"undefined\") return;",
    "  installStyles();",
    "  const applyNow = () => { ensureSelectableIds(); applySelection(); applyDrafts(); };",
    "  window.addEventListener(\"message\", handleParentMessage);",
    "  document.addEventListener(\"mousemove\", handleMouseMove, true);",
    "  document.addEventListener(\"click\", handleClick, true);",
    "  new MutationObserver(applyNow).observe(document.documentElement, { childList: true, subtree: true });",
    "  if (document.readyState === \"loading\") document.addEventListener(\"DOMContentLoaded\", applyNow, { once: true });",
    "  else applyNow();",
    "}",
    "",
    "function handleParentMessage(event: MessageEvent) {",
    "  const data = event.data || {};",
    "  if (data.type === \"design-style-drafts\") { styleDrafts = data.drafts || {}; applyDrafts(); return; }",
    "  if (data.type === \"design-selected-component\") { selectedComponentId = typeof data.id === \"string\" ? data.id : \"\"; applySelection(); return; }",
    "  if (data.type === \"design-component-hierarchy-request\" && typeof data.id === \"string\") {",
    "    ensureSelectableIds();",
    "    const node = queryById(data.id);",
    "    if (!node) return;",
    "    window.parent.postMessage({ type: \"design-component-hierarchy\", requestId: data.requestId, frameId: frameId(), id: data.id, component: describe(node, true), path: ancestorComponents(node) }, \"*\");",
    "  }",
    "}",
    "",
    "function handleMouseMove(event: MouseEvent) {",
    "  ensureSelectableIds();",
    "  const target = closestSelectable(event.target);",
    "  const id = nodeId(target);",
    "  if (id === hoverId) return;",
    "  hoverId = id;",
    "  applySelection();",
    "  if (target && id) window.parent.postMessage({ type: \"design-component-hover\", frameId: frameId(), id, component: describe(target, false), x: event.clientX, y: event.clientY }, \"*\");",
    "}",
    "",
    "function handleClick(event: MouseEvent) {",
    "  ensureSelectableIds();",
    "  const target = closestSelectable(event.target);",
    "  if (!target) return;",
    "  event.preventDefault();",
    "  event.stopPropagation();",
    "  window.parent.postMessage({ type: \"design-component-selected\", frameId: frameId(), id: nodeId(target), component: describe(target, false), ancestors: ancestorIds(target), x: event.clientX, y: event.clientY }, \"*\");",
    "}",
    "",
    "function installStyles() {",
    "  if (document.getElementById(\"aflow-design-bridge-style\")) return;",
    "  const style = document.createElement(\"style\");",
    "  style.id = \"aflow-design-bridge-style\";",
    "  style.textContent = `[data-component-id],[data-aflow-dom-id]{cursor:pointer;transition:outline-color 120ms,box-shadow 120ms}.__aflow_design_selected{outline:2px solid var(--aflow-design-outline-color,#2563eb)!important;outline-offset:-2px!important;box-shadow:inset 0 0 0 1px color-mix(in srgb,var(--aflow-design-outline-color,#2563eb),transparent 30%)!important}.__aflow_design_hover{outline:2px solid var(--aflow-design-outline-color,#0ea5e9)!important;outline-offset:-2px!important;box-shadow:inset 0 0 0 1px color-mix(in srgb,var(--aflow-design-outline-color,#0ea5e9),transparent 42%)!important}`;",
    "  document.head.appendChild(style);",
    "}",
    "",
    "function frameId() { return new URLSearchParams(window.location.search).get(\"frameId\") || window.location.pathname.replace(/^\\/+/, \"\") || \"frame\"; }",
    "function designView() { return new URLSearchParams(window.location.search).get(\"view\") || \"html\"; }",
    "function selector() { return designView() === \"wireframe\" ? \"[data-component-id]\" : \"[data-component-id],[data-aflow-dom-id]\"; }",
    "function sourcePath() { return `route:${window.location.pathname || \"/\"}`; }",
    "function nodeId(node: Element | null | undefined) { return node instanceof HTMLElement ? node.getAttribute(\"data-component-id\") || node.getAttribute(\"data-aflow-dom-id\") || \"\" : \"\"; }",
    "function queryById(id: string) { return document.querySelector(`[data-component-id=\"${CSS.escape(id)}\"],[data-aflow-dom-id=\"${CSS.escape(id)}\"]`) as DesignNode | null; }",
    "function closestSelectable(value: EventTarget | null) { return value instanceof Element ? value.closest(selector()) as DesignNode | null : null; }",
    "",
    "function ensureSelectableIds() {",
    "  if (designView() === \"wireframe\") return;",
    "  document.querySelectorAll(\"body *\").forEach((node) => {",
    "    if (!(node instanceof HTMLElement) || node.hasAttribute(\"data-component-id\") || node.hasAttribute(\"data-aflow-dom-id\")) return;",
    "    if (!isSelectable(node)) return;",
    "    node.setAttribute(\"data-aflow-dom-id\", `dom:${frameId()}:${domCounter++}`);",
    "  });",
    "}",
    "",
    "function isSelectable(node: HTMLElement) {",
    "  if (ignoredTags.has(node.tagName) || node.closest(\"[data-aflow-ignore='true'],[hidden]\")) return false;",
    "  const style = getComputedStyle(node);",
    "  if (style.display === \"none\" || style.visibility === \"hidden\" || style.pointerEvents === \"none\") return false;",
    "  return Array.from(node.getClientRects()).some((rect) => rect.width >= 3 && rect.height >= 3);",
    "}",
    "",
    "function applySelection() {",
    "  ensureSelectableIds();",
    "  document.querySelectorAll(selector()).forEach((node) => {",
    "    if (!(node instanceof HTMLElement)) return;",
    "    const id = nodeId(node);",
    "    const active = Boolean(selectedComponentId) && id === selectedComponentId;",
    "    const hover = Boolean(hoverId) && id === hoverId && !active;",
    "    if (active || hover) node.style.setProperty(\"--aflow-design-outline-color\", layerColor(node));",
    "    else node.style.removeProperty(\"--aflow-design-outline-color\");",
    "    node.classList.toggle(\"__aflow_design_selected\", active);",
    "    node.classList.toggle(\"__aflow_design_hover\", hover);",
    "  });",
    "}",
    "",
    "function applyDrafts() {",
    "  restoreDrafts();",
    "  Object.entries(styleDrafts || {}).forEach(([id, style]) => {",
    "    const node = queryById(id);",
    "    if (!node) return;",
    "    const inlineStyles: Record<string, string> = {};",
    "    Object.keys(style).forEach((key) => { if (key !== \"__aflowX\" && key !== \"__aflowY\") inlineStyles[key] = (node.style as any)[key] || \"\"; });",
    "    const rect = node.getBoundingClientRect();",
    "    node.dataset.aflowBaseInlineStyles = JSON.stringify({ styles: inlineStyles, transform: node.style.transform || \"\" });",
    "    const targetX = Number.parseFloat(String(style.__aflowX));",
    "    const targetY = Number.parseFloat(String(style.__aflowY));",
    "    const dx = Number.isFinite(targetX) ? targetX - rect.x : 0;",
    "    const dy = Number.isFinite(targetY) ? targetY - rect.y : 0;",
    "    if (dx || dy) node.style.transform = [node.style.transform || \"\", `translate(${dx}px, ${dy}px)`].filter(Boolean).join(\" \");",
    "    Object.entries(style).forEach(([key, value]) => { if (key !== \"__aflowX\" && key !== \"__aflowY\") try { (node.style as any)[key] = String(value); } catch {} });",
    "    draftedIds.add(id);",
    "  });",
    "}",
    "",
    "function restoreDrafts() {",
    "  draftedIds.forEach((id) => {",
    "    const node = queryById(id);",
    "    if (!node) return;",
    "    try {",
    "      const base = JSON.parse(node.dataset.aflowBaseInlineStyles || \"{}\");",
    "      Object.entries(base.styles || {}).forEach(([key, value]) => { (node.style as any)[key] = String(value || \"\"); });",
    "      if (typeof base.transform === \"string\") node.style.transform = base.transform;",
    "    } catch {}",
    "    delete node.dataset.aflowBaseInlineStyles;",
    "  });",
    "  draftedIds = new Set();",
    "}",
    "",
    "function describe(node: DesignNode, includeChildren: boolean) {",
    "  const explicit = node.hasAttribute(\"data-component-id\");",
    "  const text = ((node.getAttribute(\"aria-label\") || node.getAttribute(\"alt\") || node.getAttribute(\"title\") || node.getAttribute(\"data-component-name\") || node.textContent || \"\").replace(/\\s+/g, \" \").trim());",
    "  const tag = node.tagName.toLowerCase();",
    "  return {",
    "    id: nodeId(node),",
    "    name: (text ? text.slice(0, 56) : tag) + (text.length > 56 ? \"...\" : \"\"),",
    "    type: explicit ? `component:${tag}` : `dom:${tag}`,",
    "    selector: explicit ? `[data-component-id=\"${escapeAttr(nodeId(node))}\"]` : cssPath(node),",
    "    filePath: sourcePath(),",
    "    xpath: xpath(node),",
    "    tagName: tag,",
    "    textContent: text.slice(0, 240),",
    "    selectionLevel: explicit ? \"component\" : \"dom-element\",",
    "    anchorKind: explicit ? \"data-component-id\" : node.id ? \"id\" : \"xpath\",",
    "    bounds: bounds(node),",
    "    computedStyle: computedStyle(node),",
    "    description: explicit ? \"Stable React design component anchor marked with data-component-id.\" : \"Rendered React DOM element selected from the frame; it may be a nested element rather than a component boundary.\",",
    "    children: includeChildren ? Array.from(node.children).filter((child) => child.matches(selector())).slice(0, 120).map((child) => describe(child as DesignNode, false)) : [],",
    "  };",
    "}",
    "",
    "function ancestorIds(target: DesignNode) { return ancestorComponents(target).map((item) => item.id); }",
    "function ancestorComponents(target: DesignNode) {",
    "  const output: ReturnType<typeof describe>[] = [];",
    "  let node: Element | null = target;",
    "  while (node) {",
    "    node = node.closest(selector());",
    "    if (!node || !(node instanceof HTMLElement)) break;",
    "    if (!output.some((item) => item.id === nodeId(node))) output.push(describe(node as DesignNode, false));",
    "    node = node.parentElement;",
    "  }",
    "  return output.reverse();",
    "}",
    "",
    "function layerColor(node: HTMLElement) { let depth = 0; let parent = node.parentElement; while (parent) { if (parent.matches(selector())) depth += 1; parent = parent.parentElement; } return layerColors[depth % layerColors.length]; }",
    "function round(value: number) { return Math.round(value * 10) / 10; }",
    "function bounds(node: HTMLElement) { const rect = node.getBoundingClientRect(); return { x: round(rect.x), y: round(rect.y), width: round(rect.width), height: round(rect.height) }; }",
    "function computedStyle(node: HTMLElement) { const style = getComputedStyle(node); return { display: style.display, position: style.position, left: style.left, top: style.top, right: style.right, bottom: style.bottom, width: style.width, height: style.height, transform: style.transform, color: style.color, backgroundColor: style.backgroundColor, fontFamily: style.fontFamily, fontSize: style.fontSize, fontWeight: style.fontWeight, lineHeight: style.lineHeight, textAlign: style.textAlign, letterSpacing: style.letterSpacing, border: style.border, borderRadius: style.borderRadius, padding: style.padding, margin: style.margin, opacity: style.opacity, flexDirection: style.flexDirection, alignItems: style.alignItems, justifyContent: style.justifyContent, gap: style.gap, boxShadow: style.boxShadow }; }",
    "function escapeAttr(value: string) { return String(value).replace(/\\\\/g, \"\\\\\\\\\").replace(/\\\"/g, \"\\\\\\\"\"); }",
    "function cssPath(node: HTMLElement) { const parts: string[] = []; let current: HTMLElement | null = node; while (current && current.tagName !== \"BODY\" && current.tagName !== \"HTML\") { let part = current.tagName.toLowerCase(); if (current.id) { parts.unshift(`${part}#${current.id}`); break; } let nth = 1; let sibling = current.previousElementSibling; while (sibling) { if (sibling.tagName === current.tagName) nth += 1; sibling = sibling.previousElementSibling; } parts.unshift(`${part}:nth-of-type(${nth})`); current = current.parentElement; } return parts.join(\" > \"); }",
    "function xpath(node: HTMLElement) { if (node.id) return `//*[@id=\"${node.id}\"]`; if (node.getAttribute(\"data-component-id\")) return `//*[@data-component-id=\"${node.getAttribute(\"data-component-id\")}\"]`; const parts: string[] = []; let current: HTMLElement | null = node; while (current && current.tagName !== \"HTML\") { if (current.tagName !== \"BODY\") parts.unshift(xpathSegment(current)); current = current.parentElement; } return `/html/body${parts.length ? `/${parts.join(\"/\")}` : \"\"}`; }",
    "function xpathSegment(node: HTMLElement) { const tag = node.tagName.toLowerCase(); let same = 0; let index = 0; Array.from(node.parentElement?.children || []).forEach((child) => { if (child.tagName === node.tagName) { same += 1; if (child === node) index = same; } }); return same > 1 ? `${tag}[${index}]` : tag; }",
    "",
  ].join("\n");
}
