import { readdir, writeFile } from "node:fs/promises";
import { join, relative } from "node:path";

const distRoot = join(import.meta.dir, "../../ui/dist");
const outputPath = join(import.meta.dir, "../src/static-ui-assets.generated.ts");

const files = await listFiles(distRoot);
files.sort();

const imports: string[] = [];
const entries: string[] = [];

for (const [index, file] of files.entries()) {
  const name = `asset${index}`;
  const route = `/${relative(distRoot, file).replaceAll("\\", "/")}`;
  const importPath = `../../ui/dist/${route.slice(1)}`;

  imports.push(`import ${name} from "${importPath}" with { type: "file" };`);
  entries.push(`  ${JSON.stringify(route)}: ${name},`);
}

const content = `// @ts-nocheck
// This file is generated by packages/server/scripts/generate-static-ui-assets.ts.

${imports.join("\n")}

export const staticUiAssets: Record<string, string> = {
${entries.join("\n")}
};
`;

await writeFile(outputPath, content, "utf8");

async function listFiles(directory: string): Promise<string[]> {
  const output: string[] = [];
  const entries = await readdir(directory, { withFileTypes: true });

  for (const entry of entries) {
    const path = join(directory, entry.name);
    if (entry.isDirectory()) {
      output.push(...await listFiles(path));
    } else if (entry.isFile()) {
      output.push(path);
    }
  }

  return output;
}
